// ESTRUCTURA DE CONTENIDO - Organizada por MODO e INTENSIDAD
// Este archivo contiene todos los retos y verdades del juego
// IMPORTANTE: Ofuscar este archivo antes de publicar

const challenges = {
    couple: {
        soft: {
            reto: [
                "Susurra al oído de tu pareja algo que quieras hacerle más tarde.",
                "Dale a tu pareja un beso de 30 segundos únicamente en el cuello.",
                "Mantén la mirada fija en los ojos de tu pareja un minuto sin reírte.",
                "Dale a tu pareja un masaje de hombros de dos minutos.",
                "Baila con tu pareja una canción lenta, aunque no haya música.",
                "Escribe un mensaje de texto atrevido a tu pareja y envíaselo ahora.",
                "Muerde suavemente el lóbulo de la oreja de tu pareja.",
                "Recorre la cara de tu pareja con la punta de tus dedos muy lento.",
                "Dale un beso mariposa (con las pestañas) en la mejilla a tu pareja.",
                "Elige una prenda del outfit de tu pareja y quítasela.",
                "Pasa tus manos por las nalgas de tu pareja y aprieta con ropa.",
                "Refriega tu entrepierna contra el muslo de tu pareja (con ropa).",
                "Muerde el labio inferior de tu pareja y tira de él suavemente.",
                "Mete tu mano bajo la camiseta de tu pareja y acaricia su pecho.",
                "Describe al oído de tu pareja cómo le quitarías la ropa ahora.",
                "Pon a tu pareja contra la pared y presiona tu cuerpo contra el suyo.",
                "Desabrocha el cinturón o botón de tu pareja usando solo los dientes.",
                "Acaricia la zona íntima de tu pareja por encima de la ropa.",
                "Dale un beso francés con lengua, pero con tus manos en tu espalda.",
                "Siéntate en el regazo de tu pareja y muévete de forma circular.",
                "Escribe una palabra atrevida en la espalda de tu pareja con tu lengua.",
                "Dale a tu pareja un beso de 1 minuto sin usar las manos.",
                "Pasa tus labios por el cuello de tu pareja sin llegar a tocar su piel.",
                "Haz un baile sexy de 30 segundos frente a tu pareja.",
                "Dale a tu pareja un masaje de manos muy lento y sugerente.",
                "Muerde el hombro de tu pareja suavemente por encima de la ropa.",
                "Susurra a tu pareja qué le harías si estuviéramos en un cine.",
                "Desabrocha un botón de la camisa o blusa de tu pareja.",
                "Acaricia el muslo de tu pareja y sube hasta donde te permita la ropa.",
                "Dale un beso francés intenso que dure al menos 40 segundos.",
                "Muerde tu labio inferior mientras miras a tu pareja con deseo.",
                "Recorre el contorno de los labios de tu pareja con tu dedo índice.",
                "Abraza a tu pareja por la espalda y aprieta tus manos contra su pecho.",
                "Toca las nalgas de tu pareja y dale un apretón firme (con ropa).",
                "Dile a tu pareja tres cosas que te encantan de su cuerpo ahora mismo.",
                "Quítate una prenda de ropa de forma muy lenta y provocativa.",
                "Pasa tus manos por todo el cuerpo de tu pareja sin despegar la vista.",
                "Dale un beso en la frente y luego baja lentamente hasta su boca.",
                "Camina de forma sexy hacia tu pareja y siéntate en su regazo.",
                "Sujeta el rostro de tu pareja y dale un beso corto pero muy húmedo."
            ],
            verdad: [
                "¿Qué fue lo primero que pensaste al verme hoy?",
                "¿Cuál es tu parte favorita de mi cuerpo cuando estoy con ropa?",
                "¿Qué prenda de las que llevo puesta te gustaría quitarme primero?",
                "¿Cuál es tu recuerdo favorito de nuestra primera vez?",
                "¿Qué es lo más romántico o sexy que he hecho por ti?",
                "¿Tienes alguna fantasía inocente que nunca me hayas dicho?",
                "¿Qué olor mío te vuelve más loco/a?",
                "¿Dónde sería el lugar público más arriesgado donde lo harías?",
                "¿Qué es lo que más te gusta de mi actitud en la cama?",
                "¿Cuál es el cumplido sexual que más te gusta recibir?",
                "¿Qué prenda de mi ropa te estorba más en este momento?",
                "¿Alguna vez has fantaseado conmigo en un lugar público?",
                "¿Qué sonido hago que más te excita cuando estamos juntos?",
                "¿Te gusta que te agarre del cabello mientras nos besamos?",
                "¿Cuál es la fantasía que más te da curiosidad probar conmigo?",
                "¿Qué parte de mi cuerpo desnudo te mueres por tocar ahora?",
                "¿Prefieres que sea yo quien tome la iniciativa hoy?",
                "¿Cuál es el lugar de tu cuerpo donde más te gusta que te bese?",
                "¿Qué es lo más atrevido que has pensado hoy al verme?",
                "¿Te gustaría que hoy el encuentro fuera lento o rápido?",
                "¿Qué es lo que más te gusta que te diga al oído?",
                "¿Cuál es tu recuerdo favorito de nosotros en la cama?",
                "¿Qué prenda de ropa mía te resulta más difícil de ignorar?",
                "¿Te gustaría que hoy probáramos algún lugar nuevo de la casa?",
                "¿Cuál es la parte de mi cuerpo que más te gusta acariciar?",
                "¿Qué tan rápido se aceleró tu pulso cuando empezamos a jugar?",
                "¿Prefieres que te bese con mucha o con poca lengua?",
                "¿Cuál es el lugar público más arriesgado donde lo harías?",
                "¿Te gusta que te mire fijamente cuando nos besamos?",
                "¿Qué es lo primero que me quitarías si pudieras ahora mismo?",
                "¿Alguna vez has tenido un sueño erótico conmigo y otro alguien?",
                "¿Qué sonido mío te indica que estoy disfrutando de verdad?",
                "¿Te gusta que te domine o que yo sea quien guíe hoy?",
                "¿Cuál es tu mayor fantasía romántica que sea también sexy?",
                "¿Qué es lo que más te gusta de mi ropa interior?",
                "¿Prefieres el sexo con música o con nuestros propios sonidos?",
                "¿Te excita que te agarre las manos mientras me besas?",
                "¿Cuál es el cumplido que más te ha hecho sonrojar?",
                "¿Qué te gustaría que te hiciera hoy que nunca te he hecho?",
                "¿Te gusta que te hable durante el acto o prefieres silencio?",
                "¿En qué momento del día piensas más en tener sexo conmigo?",
                "¿Qué ropa interior mía te pone más caliente?",
                "¿Prefieres que te bese primero o que te toque primero?",
                "¿Cuál es el apodo sucio que te gustaría que te dijera?",
                "¿Te gusta más cuando voy rápido o cuando voy lento?",
                "¿Qué es lo primero que se te vino a la mente cuando me viste hoy?",
                "¿En qué posición te gusta verme más?",
                "¿Qué tan seguido te tocas pensando en mí?",
                "¿Dónde te gustaría que te dejara una marca con mis dientes?",
                "¿Te excita más que te agarre del pelo o de la cintura?"
            ]
        },
        sensual: {
            reto: [
                "Quítate dos prendas de ropa de tu elección.",
                "Dibuja una línea con tu lengua desde la barbilla de tu pareja al ombligo.",
                "Quítale una prenda a tu pareja usando solo tus dientes.",
                "Recorre la espalda de tu pareja con un hielo o con tus labios.",
                "Venda los ojos de tu pareja y bésale en tres lugares sorpresa.",
                "Pon tus manos bajo la ropa de tu pareja, directo en su piel, 1 minuto.",
                "Dale un masaje en los pies a tu pareja de forma muy sugerente.",
                "Lame el cuello de tu pareja y dile a qué sabe su piel.",
                "Siéntate en el regazo de tu pareja y bésale apasionadamente.",
                "Quítale los zapatos y las medias a tu pareja con mucha calma.",
                "Chupa uno de tus dedos lentamente como si fuera el sexo de tu pareja.",
                "Desabrocha el pantalón o falda de tu pareja y deja que caiga al suelo.",
                "Quítate la ropa interior y quédate solo con la prenda de arriba.",
                "Simula que das sexo oral a tu pareja usando solo su muslo interno.",
                "Desliza tus labios fríos (o un hielo) por todo el vientre de tu pareja.",
                "Lame el pecho de tu pareja y baja hasta su ombligo muy despacio.",
                "Dale a tu pareja tres azotes en las nalgas sobre la piel desnuda.",
                "Mastúrbate frente a tu pareja durante un minuto sin que te toque.",
                "Pon tu cara entre las piernas de tu pareja y respira sobre su ropa interior.",
                "Pon la mano de tu pareja directamente sobre tus genitales (piel a piel).",
                "Quítate la ropa interior por debajo de tu pantalón o falda.",
                "Lame los pezones de tu pareja por encima de su ropa interior.",
                "Pasa tu lengua por el abdomen de tu pareja hasta llegar al elástico.",
                "Pon tu cara entre las piernas de tu pareja y respira sobre su ropa.",
                "Masajea los genitales de tu pareja por encima de su ropa interior.",
                "Deja que tu pareja te quite una prenda usando solo sus dientes.",
                "Unta un poco de tu bebida en tu cuello y deja que tu pareja la lama.",
                "Acaricia el sexo de tu pareja por debajo de la ropa (pero con bragas/bóxer).",
                "Dale a tu pareja tres nalgadas suaves directamente en la piel desnuda.",
                "Lame tus dedos y pásalos por los labios de tu pareja muy despacio.",
                "Desabrocha el sujetador o ropa interior de tu pareja con una mano.",
                "Refriega tu entrepierna contra el muslo de tu pareja (piel con piel).",
                "Muerde los muslos de tu pareja cerca de su zona íntima.",
                "Quítate toda la ropa exterior y quédate solo en ropa interior.",
                "Haz un baile erótico (lap dance) rozando tu sexo con el de tu pareja.",
                "Recorre con tu lengua el cuerpo de tu pareja desde el cuello al ombligo.",
                "Pasa un hielo o tus labios fríos por la espalda desnuda de tu pareja.",
                "Pon la mano de tu pareja en tu zona íntima (por encima de la ropa).",
                "Muerde suavemente el lóbulo de tu pareja y luego sóplale.",
                "Túmbate y deja que tu pareja te explore por debajo de la ropa.",
                "Quítale la ropa interior a tu pareja sin usar las manos",
                "Chupa el cuello de tu pareja hasta dejarle una marca visible",
                "Pon hielo en tu boca y besa el vientre de tu pareja",
                "Mete tu mano dentro del pantalón de tu pareja y acaricia 30 segundos",
                "Muerde las nalgas de tu pareja sobre la piel desnuda",
                "Masajea los genitales de tu pareja por encima de su ropa interior",
                "Lame desde el ombligo de tu pareja hasta su cuello muy despacio",
                "Quítate toda la ropa y deja que tu pareja te mire 1 minuto",
                "Frota tu entrepierna contra la pierna de tu pareja hasta que gimas",
                "Dale tres nalgadas fuertes a tu pareja y dile algo sucio"
            ],
            verdad: [
                "¿Qué zona de tu cuerpo es la más sensible al tacto?",
                "¿Prefieres dominar o ser dominado/a en la cama?",
                "¿Cuál es la posición que más te hace disfrutar?",
                "¿Qué es lo que más te gusta que te haga con las manos?",
                "¿Has tenido un sueño erótico conmigo recientemente?",
                "¿Qué juguete o accesorio te daría curiosidad probar hoy?",
                "¿Qué tan importante es el juego previo para ti del 1 al 10?",
                "¿Cuál es la actitud que más te la baja en el aspecto sexual?",
                "¿Te gusta que te hablen sucio o prefieres el silencio?",
                "¿Prefieres hacerlo con luz encendida o apagada?",
                "¿Cómo describirías el sabor de mi piel cuando estás excitado/a?",
                "¿Qué es lo que más te gusta ver cuando me estás desnudando?",
                "¿Te gusta que te mire fijamente mientras me tocas?",
                "¿Cuál es tu posición favorita para recibir sexo oral?",
                "¿Te excita verme tocarme a mí mismo/a mientras me miras?",
                "¿Qué olor de mi cuerpo te despierta más el apetito sexual?",
                "¿Prefieres que te muerda o que te lama las zonas sensibles?",
                "¿Cuál es el cumplido más sucio que te han dicho?",
                "¿Alguna vez has deseado usar comida en la cama?",
                "¿Sientes alguna pulsación en tu zona íntima ahora mismo?",
                "¿Qué es lo que más te gusta ver cuando me desnudo para ti?",
                "¿Te gustaría que usáramos una venda o esposas hoy?",
                "¿Qué zona de tu cuerpo crees que tengo descuidada?",
                "¿Te excita sentir mi respiración en tu zona íntima?",
                "¿Cuál es tu posición favorita para el juego previo?",
                "¿Te gusta que te muerda los muslos internos?",
                "¿Qué olor de mi cuerpo te resulta más afrodisíaco?",
                "¿Te gustaría que te tocara mientras me miras a los ojos?",
                "¿Cuál es el lugar más sensible de tu espalda?",
                "¿Qué tan mojada/erecto estás en este preciso momento?",
                "¿Te gusta que te hable sucio o que sea más tierno/a?",
                "¿Cuál es tu mayor fantasía de perreo intenso?",
                "¿Qué juguete sexual te gustaría que incorporáramos hoy?",
                "¿Te excita que te susurre lo que te voy a hacer en un momento?",
                "¿Prefieres que use mis manos o mi boca para preliminares?",
                "¿Qué parte de mi cuerpo quieres que lama durante 5 minutos?",
                "¿Te gusta que te venda los ojos mientras te acaricio?",
                "¿Cuál es la parte que más te calienta de otra persona",
                "¿Te gustaría que grabáramos solo el audio de hoy?",
                "¿Qué tan cerca estás de querer pasar al siguiente nivel?",
                "¿Qué tan mojado/duro estás ahora mismo del 1 al 10?",
                "¿Cuántas veces has acabado pensando en mí esta semana?",
                "¿Qué posición te hace sentir más lleno/a o más profundo?",
                "¿Te gusta que te escupa en la boca mientras lo hacemos?",
                "¿Prefieres que te penetre con los dedos o con la lengua primero?",
                "¿Qué tan fuerte te gusta que te azoten las nalgas?",
                "¿Te gustaría que usáramos un espejo para vernos mientras lo hacemos?",
                "¿Cuál es el lugar más atrevido donde me has querido tomar?",
                "¿Te excita más cuando te hablo sucio o cuando gimo?",
                "¿Prefieres acabar rápido y varias veces, o aguantar mucho una vez?"
            ]
        },
        hardcore: {
            reto: [
                "Quédate sin nada de ropa durante el resto del juego.",
                "Practica sexo oral a tu pareja durante 2 minutos seguidos.",
                "Elige tu posición favorita y úsala con tu pareja ahora mismo.",
                "Usa tus manos para estimular a tu pareja hasta que pida que pares.",
                "Dale a tu pareja cinco azotes fuertes en las nalgas.",
                "Quítate toda la ropa de la forma más sexy que puedas.",
                "Muestra a tu pareja exactamente cómo te gusta que te toquen ahí abajo.",
                "Usa a tu pareja como tu juguete personal durante 5 minutos.",
                "Hazle un baile erótico (lap dance) a tu pareja muy cerca de su cara.",
                "Pon a tu pareja en la posición que quieras y bésale donde más le guste.",
                "Practica sexo oral a tu pareja hasta que esté a punto de llegar al clímax.",
                "Penetra a tu pareja (o déjate penetrar) en la posición que elijas.",
                "Haz que tu pareja llegue al orgasmo usando solo tus manos y boca.",
                "Pon a tu pareja en una posición vulnerable y tómala a tu antojo.",
                "Ten sexo con tu pareja mientras se miran fijamente a los ojos.",
                "Lame la zona anal de tu pareja antes de iniciar la penetración.",
                "Hazle un striptease total a tu pareja y luego tómala donde estén.",
                "Masturba a tu pareja mientras te penetra (o viceversa) para llegar juntos.",
                "Quédate inmóvil y deja que tu pareja te haga lo que quiera 3 minutos.",
                "Toma a tu pareja por detrás y dile al oído todo lo que vas a hacerle.",
                "Practica sexo oral a tu pareja hasta que esté a punto de llegar.",
                "Penetra a tu pareja (o déjate penetrar) en tu posición favorita.",
                "Haz que tu pareja llegue al orgasmo usando solo tu boca.",
                "Mastúrba a tu pareja (piel con piel) mientras la besas con pasión.",
                "Ponte en una posición vulnerable y deja que tu pareja te use.",
                "Lame el sexo (o zona anal) de tu pareja sin ninguna censura.",
                "Ten sexo con tu pareja mientras ambos se miran al espejo (si hay).",
                "Practica el 69 con tu pareja hasta que uno de los dos no aguante más.",
                "Usa mucha saliva y lame los genitales de tu pareja con intensidad.",
                "Toma a tu pareja por detrás y dile todo lo que le estás sintiendo.",
                "Mastúrbate frente a tu pareja mientras ella te toca otra parte del cuerpo.",
                "Dale a tu pareja 5 nalgadas fuertes y luego bésala donde más le guste.",
                "Penetra a tu pareja y cambia de ritmo cada vez que ella te lo pida.",
                "Quédate inmóvil y deja que tu pareja te haga un oral durante 3 minutos.",
                "Haz que tu pareja llegue al clímax usando solo tus dedos y lengua.",
                "Atale las manos a tu pareja con una prenda y tómala a tu antojo.",
                "Lame los genitales de tu pareja y luego deja que ella lo haga contigo.",
                "Ten sexo con tu pareja en una posición que nunca hayamos probado.",
                "Masturba a tu pareja y, justo antes de que llegue, detente y bésala.",
                "Penetra a tu pareja y no pares hasta que ambos hayan llegado al clímax.",
                "Lame el ano de tu pareja por 30 segundos",
                "Deja que tu pareja te penetre con los dedos hasta que estés a punto de acabar",
                "Ponte en cuatro y deja que tu pareja te tome como quiera durante 2 minutos",
                "Chupa los genitales de tu pareja mientras te masturbas",
                "Deja que tu pareja eyacule donde más le guste de tu cuerpo",
                "Masturba a tu pareja con tu boca hasta que casi se venga",
                "Penetra a tu pareja sin moverte y déjala moverse como quiera",
                "Deja que tu pareja te use la boca como si fuera tu vagina/pene",
                "Ponte de espaldas y deja que tu pareja te penetre sorpresivamente",
                "Haz el 69 con tu pareja hasta que uno de los dos casi acabe"
            ],
            verdad: [
                "¿Dónde ha sido el lugar más extraño donde has acabado?",
                "Si grabáramos un video hoy, ¿qué te gustaría que hiciéramos?",
                "¿Cuál es ese fetiche que te da vergüenza admitir?",
                "¿Qué es lo más sucio que has pensado sobre mí esta semana?",
                "¿Te gustaría probar el intercambio de roles hoy?",
                "¿Cuál ha sido tu mejor orgasmo conmigo y por qué?",
                "¿Hay alguna zona prohibida que quieras que explore hoy?",
                "¿Qué tan rápido crees que podrías hacerme llegar hoy?",
                "¿Prefieres el sexo lento y apasionado o rápido y salvaje?",
                "¿Qué es lo que más te gusta de mi cuerpo totalmente desnudo?",
                "¿Quieres que hoy termine dentro de ti o en otra parte?",
                "¿Cuál es la posición en la que te sientes más sucio/a?",
                "¿Te gustaría que hoy terminara en tu cara o en tu boca?",
                "¿Qué es lo más extremo que estarías dispuesto/a a probar hoy?",
                "¿Te gusta que te diga palabras degradantes mientras lo hacemos?",
                "¿Cuál es el lugar de mi cuerpo que quieres que quede marcado?",
                "¿Quieres que sea yo quien lleve el ritmo o prefieres el control?",
                "¿Prefieres que te agarre del cuello o te sujete las manos?",
                "¿Qué parte de mi cuerpo quieres morder al llegar al clímax?",
                "¿Cuál es el límite que quieres que empujemos hoy?",
                "¿Dónde quieres que termine hoy: dentro, fuera o en tu cara?",
                "¿Cuál es la posición que más rápido te hace llegar al clímax?",
                "¿Te gustaría que usáramos algún lubricante de sabor hoy?",
                "¿Qué es lo más salvaje que has querido hacerme y no te atreves?",
                "¿Prefieres que terminemos al mismo tiempo o uno tras otro?",
                "¿Te gusta que te agarre del cuello suavemente mientras penetro?",
                "¿Cuál es la palabra más sucia que quieres que te diga ahora?",
                "¿Te excita que te sujete las manos por encima de la cabeza?",
                "¿Qué parte de mi cuerpo quieres que quede empapada hoy?",
                "¿Te gustaría probar el sexo anal en esta sesión?",
                "¿Cuál es el límite que hoy sí te gustaría cruzar conmigo?",
                "¿Te gusta que sea rudo/a o prefieres que sea intenso pero lento?",
                "¿Qué es lo que más te gusta sentir cuando estoy dentro de ti?",
                "¿Te gustaría que usáramos algún disfraz o rol hoy?",
                "¿Prefieres que te mire a los ojos o que te hable al oído al acabar?",
                "¿Cuál es tu fantasía de dominación favorita con nosotros?",
                "¿Te gustaría que hoy la sesión fuera especialmente ruidosa?",
                "¿Qué sensación prefieres: la profundidad o la fricción?",
                "¿Cuál es el lugar de mi cuerpo que más quieres morder hoy?",
                "¿Estás listo/a para que te haga perder el control por completo?",
                "¿Dónde quieres que acabe hoy: dentro, en tu cara, en tu boca o en tus pechos?",
                "¿Qué tan profundo te gusta sentirlo cuando me penetras?",
                "¿Te gustaría que te grabara mientras te masturbo?",
                "¿Prefieres que te folle duro y rápido o lento y profundo?",
                "¿Qué tan sucio te gusta que te hable mientras estamos en eso?",
                "¿Te gustaría que te atara las manos mientras te como?",
                "¿Alguna vez has querido que acabe en tu cara?",
                "¿Qué tan apretado/grande se siente cuando entro/me penetras?",
                "¿Te gustaría usar un dildo/vibrador juntos mientras lo hacemos?",
                "¿Cuál es tu límite: algo que nunca harías en la cama?"
            ]
        }
    },
    group: {
        soft: {
            reto: [
                "Dale un beso en la mejilla a la persona de tu derecha y a la de tu izquierda.",
                "Elige a alguien y susúrrale al oído qué prenda le quitarías primero.",
                "Hazle un masaje de hombros a las dos personas que tengas a los lados.",
                "Camina de forma sexy por el centro del grupo como si fuera una pasarela.",
                "Dale un abrazo demasiado largo (15 segundos) a la persona que elijas.",
                "Deja que el grupo elija a alguien para que te dé un azote con ropa.",
                "Escribe un mensaje atrevido al grupo de WhatsApp donde estén todos.",
                "Siéntate en el regazo de la persona que elijas durante un turno completo.",
                "Muerde suavemente el hombro de la persona que tengas enfrente.",
                "Quítale una prenda de ropa a la persona que elijas (solo una).",
                "Haz un baile sexy de 30 segundos en el centro del círculo.",
                "Recorre el cuello de alguien con la punta de tus dedos.",
                "Toca las nalgas de dos personas diferentes (por encima de la ropa).",
                "Quítate una prenda de ropa y lánzasela a alguien del grupo.",
                "Pasa tu lengua por el lóbulo de la oreja de la persona a tu izquierda.",
                "Deja que alguien del grupo te desabroche un botón de la camisa.",
                "Mira fijamente a alguien a los ojos mientras te muerdes el labio.",
                "Pon tus manos bajo la camiseta de la persona que elijas (en la espalda).",
                "Dale un beso de 10 segundos en el cuello a la persona más alta del grupo.",
                "Elige a alguien para que te dé de beber algo de forma muy lenta.",
                "Elige a alguien y dibuja letras con tu dedo en su palma hasta que adivine la palabra sexo.",
                "Dale un beso de esquimal (frotar narices) a la persona más tímida del grupo.",
                "Pasa tus manos por el cabello de alguien mientras le dices un cumplido atrevido.",
                "Haz un desfile sexy alrededor del grupo y deja que alguien te dé una nalgada (con ropa).",
                "Muerde tu propio labio mientras miras fijamente a la persona que más te atrae.",
                "Susurra al oído de la persona de tu izquierda qué posición te gustaría probar con ella.",
                "Elige a alguien para que te haga un masaje de cuello de un minuto.",
                "Quítate las medias de la forma más provocativa que puedas.",
                "Pasa tu nariz por el cuello de alguien y aspira profundamente su aroma.",
                "Dale un beso en la mano a cada persona del grupo de forma muy sensual.",
                "Desabrocha dos botones de tu propia camisa/blusa y quédate así.",
                "Acaricia la rodilla de alguien y ve subiendo la mano hasta que esa persona te detenga.",
                "Elige a alguien para que te dé de comer un snack o fruta de forma sexy.",
                "Haz un movimiento de perreo lento contra la pierna de alguien del grupo.",
                "Pon tus manos en la cintura de la persona que elijas y acércala a ti.",
                "Describe en voz alta el outfit de alguien y cómo se lo quitarías.",
                "Bebe un trago de tu bebida sin usar las manos, que alguien más sostenga el vaso.",
                "Dale un beso mariposa (con las pestañas) en el cuello a alguien.",
                "Deja que alguien del grupo te dibuje un corazón en el brazo con su lengua.",
                "Escribe tu nombre en el muslo de alguien usando solo tu dedo índice.",
                "Besa en la frente a todos los del grupo, uno por uno",
                "Elige a alguien y dale un masaje en los pies durante 1 minuto",
                "Haz un cumplido sexual a cada persona del grupo",
                "Elige a dos personas y báilales de forma seductora",
                "Toca las piernas de las dos personas a tus lados simultáneamente",
                "Dale un chupetón en el cuello a la persona que el grupo elija",
                "Quítate dos prendas de ropa y déjaselas a alguien del grupo",
                "Recorre con tu lengua el brazo de la persona más cercana",
                "Siéntate entre dos personas y abrázalas por el cuello",
                "Elige a alguien y muérdele suavemente el hombro"
            ],
            verdad: [
                "¿Quién de los presentes te parece más atractivo/a hoy?",
                "¿A qué persona del grupo le confiarías un secreto erótico?",
                "¿Quién crees que es la persona más atrevida en la cama de aquí?",
                "¿Con qué dos personas de aquí harías un trío?",
                "¿Qué es lo primero que le miras a un desconocido/a?",
                "¿Quién del grupo crees que tiene la mejor retaguardia?",
                "¿Alguna vez has tenido una fantasía con alguien de este grupo?",
                "¿Prefieres ser el centro de atención o mirar desde la sombra?",
                "¿Qué prenda de alguien de aquí te gustaría ver en el suelo?",
                "¿A quién de aquí besarías si fuera el fin del mundo?",
                "¿Qué es lo más loco que has hecho en una fiesta?",
                "¿Quién de aquí crees que besa mejor sin haberlo probado?",
                "¿Te gustaría ver a dos personas de aquí besándose?",
                "¿Cuál es tu técnica de seducción infalible?",
                "¿Alguna vez te han pillado teniendo sexo?",
                "¿Qué tipo de ropa interior llevas puesta ahora mismo?",
                "¿Quién del grupo tiene la voz más sexy?",
                "¿Te daría morbo que el grupo te viera besar a alguien?",
                "¿Cuál es la parte de tu cuerpo que más te gusta exhibir?",
                "¿A quién elegirías para pasar una noche en una isla desierta?",
                "¿Quién de aquí crees que tiene la mirada más pecaminosa?",
                "¿Cuál es la prenda de ropa que más te costaría quitarte frente a todos?",
                "¿Quién del grupo crees que tiene las manos más hábiles?",
                "¿Alguna vez has fantaseado con hacer un trío con extraños?",
                "¿Qué es lo que más te atrae de la persona a tu derecha?",
                "¿A quién de aquí invitarías a una fiesta privada después de esta?",
                "¿Prefieres que te seduzcan con palabras o con contacto físico?",
                "¿Cuál es el lugar más público donde has tenido un faje?",
                "¿Quién de aquí crees que es el más salvaje en la intimidad?",
                "¿Qué te da más curiosidad probar en un grupo: mirar o participar?",
                "¿Cuál es tu placer culposo en el sexo?",
                "¿Qué persona del grupo crees que es la más difícil de seducir?",
                "¿Te gustaría ver a alguien de aquí bailando sin ropa?",
                "¿Quién crees que tiene el mejor movimiento de cadera aquí?",
                "¿Alguna vez has grabado un audio erótico para alguien?",
                "¿Cuál es el cumplido más sucio que te han dicho en un grupo?",
                "¿Prefieres la luz tenue o la oscuridad total para jugar?",
                "¿Quién de aquí tiene la sonrisa que más te hace pensar en sexo?",
                "¿Te daría morbo que te vendaran los ojos ahora mismo?",
                "¿A quién de aquí le pedirías un baile erótico privado?",
                "¿Quién del grupo tiene las manos que más te gustaría sentir en tu cuerpo?",
                "¿Con qué dos personas harías un trío aquí mismo?",
                "¿A quién del grupo le darías sexo oral sin dudarlo?",
                "¿Quién crees que tiene el mejor trasero del grupo?",
                "¿Te gustaría ver a tu pareja besando a alguien de aquí?",
                "¿Qué persona del grupo crees que gime más fuerte?",
                "¿A quién elegirías para tener sexo rápido en el baño?",
                "¿Quién del grupo crees que es el más dominante en la cama?",
                "¿Te excitaría que todos te vieran desnudo/a?",
                "¿Con qué pareja del grupo te gustaría intercambiar?"
            ]
        },
        sensual: {
            reto: [
                "Quítate la camiseta/blusa y quédate así tres turnos.",
                "Elige a dos personas para que te den un beso doble (sándwich).",
                "Chupa el dedo de alguien del grupo de forma muy sugerente.",
                "Quítale una prenda de ropa a alguien usando solo tus dientes.",
                "Deja que alguien del grupo lama una gota de bebida de tu cuello.",
                "Hazle un baile erótico (lap dance) a la persona que el grupo elija.",
                "Quédate en ropa interior delante de todos durante un minuto.",
                "Besa a la persona de tu derecha en la boca con lengua.",
                "Deja que el grupo elija a alguien para que te muerda el muslo.",
                "Toca la zona íntima de alguien por encima de su ropa interior.",
                "Quítale los pantalones o la falda a la persona que tienes enfrente.",
                "Deja que dos personas del grupo te besen el cuello al mismo tiempo.",
                "Simula una posición sexual con la persona de tu derecha (con ropa).",
                "Bebe un trago de tu copa directamente del ombligo de alguien.",
                "Quítate la ropa interior sin quitarte los pantalones/falda.",
                "Elige a alguien y recorre su columna vertebral con tu lengua.",
                "Pide a alguien que te vende los ojos y adivina quién te está besando.",
                "Masajea los genitales de alguien por encima de la ropa durante 1 min.",
                "Desabrocha el sujetador o la ropa interior de alguien solo con una mano.",
                "Lame el lóbulo de la oreja de la persona más bajita del grupo.",
                "Quítate una prenda de ropa interior sin quitarte la ropa exterior.",
                "Elige a dos personas para que te acaricien los muslos al mismo tiempo.",
                "Pasa tu lengua por el borde de la ropa interior de alguien (sin tocar piel genital).",
                "Deja que alguien del grupo te muerda suavemente el abdomen desnudo.",
                "Unta un poco de bebida en tu pecho y deja que alguien la lama.",
                "Simula que recibes sexo oral de alguien por encima de su ropa.",
                "Pasa tu lengua por el elástico de la ropa interior de la persona a tu derecha.",
                "Pon tu cara entre las piernas de alguien y gime como si estuvieras en el acto.",
                "Deja que alguien te desabroche el sujetador/ropa interior bajo la ropa.",
                "Elige a alguien y acaricia su entrepierna por encima del pantalón/falda 1 min.",
                "Quédate en ropa interior y deja que el grupo decida quién te da 3 azotes.",
                "Pasa tu lengua por los pezones de alguien a través de su camiseta.",
                "Pon la mano de alguien en tu zona íntima (por encima de la ropa).",
                "Lame el cuello de alguien y ve bajando hasta el inicio de sus genitales.",
                "Haz un baile erótico para el grupo y quédate solo con una prenda puesta.",
                "Aprieta las nalgas de alguien (piel con piel) pero por debajo de su ropa.",
                "Deja que alguien te eche el aliento caliente en la entrepierna (con ropa).",
                "Elige a una persona y recorre sus muslos internos con tus labios.",
                "Toca el sexo de alguien por encima de la ropa interior mientras le besas.",
                "Susúrrale a alguien qué le harías si no hubiera ropa de por medio.",
                "Besa a las dos personas de tus lados en la boca al mismo tiempo",
                "Deja que alguien te quite la ropa interior con los dientes",
                "Elige a alguien y frota tu entrepierna contra su muslo",
                "Dale un beso negro a la persona que el grupo elija",
                "Toca los genitales de dos personas al mismo tiempo (sobre ropa)",
                "Lame el sudor del cuello de la persona más cercana",
                "Besa los pezones de alguien sobre la ropa por 15 segundos",
                "Deja que dos personas te chupen el cuello al mismo tiempo",
                "Elige a alguien y mastúrbalo/a por encima de su ropa 30 segundos",
                "Quédate en ropa interior y baila sensualmente para el grupo"
            ],
            verdad: [
                "¿Qué persona del grupo crees que tiene el olor más excitante?",
                "¿A quién de los presentes elegirías para un intercambio rápido?",
                "¿Qué es lo que más te gusta mirar cuando dos personas se besan?",
                "¿Cuál de los presentes crees que es el más sucio en la cama?",
                "¿Qué te daría más morbo: que te miren o mirar tú a los demás?",
                "¿A quién de aquí le darías un beso negro?",
                "¿Quién del grupo crees que tiene los pezones más sensibles?",
                "¿Alguna vez has fantaseado con un trío con personas de aquí?",
                "¿Qué parte de tu cuerpo te gustaría que todos tocaran ahora?",
                "¿A quién de aquí invitarías a una ducha erótica grupal?",
                "¿Quién de aquí crees que es más ruidoso/a en la cama?",
                "¿Te gustaría participar en un intercambio de parejas hoy?",
                "¿Qué es lo que más te excita de ver a otros besándose?",
                "¿Has hecho un trío o te gustaría intentarlo con alguien de aquí?",
                "¿Quién de aquí tiene el mejor cuerpo desnudo, según imaginas?",
                "¿Te atrae sexualmente más de una persona de este grupo?",
                "¿Qué posición te gustaría probar con dos personas de aquí?",
                "¿Cuál es tu opinión real sobre las orgías o el sexo grupal?",
                "¿A quién dejarías que te vendará los ojos para tocarte?",
                "¿Te excita que te miren mientras besas a alguien?",
                "¿A quién del grupo dejarías que te desnudara por completo?",
                "¿Te excita ver a dos personas del mismo sexo besándose?",
                "¿Cuál es el fetiche más extraño que te gustaría cumplir aquí?",
                "¿Quién crees que tiene la piel más sensible al tacto?",
                "¿Te gustaría recibir un masaje con aceite frente a todos?",
                "¿Qué persona de aquí te daría más morbo ver masturbándose?",
                "¿Preferirías que te tocaran o tocar tú a todos los presentes?",
                "¿Cuál es la parte de tu cuerpo que más te excita que laman?",
                "¿A quién de aquí le pedirías que te azotara ahora mismo?",
                "¿Te excita que te hablen sucio mientras te tocan con ropa?",
                "¿Quién de aquí crees que gime más fuerte cuando le dan placer?",
                "¿Alguna vez has tenido un orgasmo solo con caricias y ropa?",
                "¿Qué es lo más atrevido que estarías dispuesto a hacer hoy?",
                "¿A quién de aquí le permitirías que te vende los ojos para tocarte?",
                "¿Te gustaría ver un striptease grupal en este momento?",
                "¿Quién del grupo tiene el trasero más provocativo bajo la ropa?",
                "¿Qué olor corporal de los presentes te atrae más?",
                "¿Prefieres que te muerdan o que te succionen la piel?",
                "¿Te excita la idea de que alguien te toque mientras otros miran?",
                "¿Quién de aquí crees que es el más sucio verbalmente?",
                "¿A quién del grupo le pedirías que te penetre con los dedos?",
                "¿Quién del grupo crees que tiene el mejor sexo oral?",
                "¿Te gustaría que dos personas del grupo te estimularan a la vez?",
                "¿Cuál es tu fantasía con más de una persona de aquí?",
                "¿A quién del grupo dejarías que eyaculara en tu cara?",
                "¿Te gustaría que todos te tocaran las zonas íntimas al mismo tiempo?",
                "¿Con qué persona compartirías tu pareja por una noche?",
                "¿Quién crees que tiene el pene/vagina más grande/apretada aquí?",
                "¿Te excitaría masturbarte mientras todos te miran?",
                "¿A cuántas personas del grupo te follarías en una noche?"
            ]
        },
        hardcore: {
            reto: [
                "Practica sexo oral a la persona que elijas frente a los demás.",
                "Elige a dos personas para que estimulen tus zonas íntimas a la vez.",
                "Mastúrbate frente al grupo hasta que alguien te pida que pares.",
                "Deja que dos personas del grupo te quiten absolutamente toda la ropa.",
                "Ten relaciones sexuales con alguien mientras el resto del grupo observa.",
                "Lame la zona íntima de la persona que tienes a tu izquierda (sin ropa).",
                "Deja que alguien te penetre (con dedos o juguete) frente a todos.",
                "Haz un trío rápido (estimulación mutua) con las dos personas más cercanas.",
                "Deja que el grupo decida en qué parte de tu cuerpo quieren eyacular.",
                "Elige a una persona y tómala por detrás mientras los demás se tocan.",
                "Practica sexo oral a la persona de tu derecha mientras la de la izquierda te mira.",
                "Deja que dos personas usen sus manos en tus zonas íntimas a la vez.",
                "Mastúrbate frente a todos usando un objeto o juguete que haya cerca.",
                "Quítate toda la ropa y deja que el grupo te dé nalgadas por turnos.",
                "Elige a alguien para tener sexo oral mutuo (69) frente al grupo.",
                "Recorre con tu lengua el sexo de alguien hasta que esa persona gima.",
                "Penetra a alguien (o déjate penetrar) en la posición que el grupo elija.",
                "Deja que alguien te ate las manos y te estimule como prefiera.",
                "Haz que dos personas del grupo se besen mientras tú las tocas a ambas.",
                "Elige a tu pareja de turno y haz que llegue al orgasmo frente a todos.",
                "Practica sexo oral a la persona que elijas hasta que suplique que pares.",
                "Ten relaciones con alguien mientras otra persona te masturba por detrás.",
                "Lame el sexo de la persona de tu izquierda durante un minuto completo.",
                "Elige a dos personas para que te den placer oral al mismo tiempo.",
                "Mastúrbate frente al grupo y deja que alguien elija dónde debes terminar.",
                "Penetra a alguien (o déjate penetrar) en el centro de la habitación.",
                "Deja que alguien te penetre mientras tú le das un oral a una tercera persona.",
                "Usa tu lengua en la zona anal de la persona que el grupo elija.",
                "Ten sexo con alguien en una posición donde todos puedan ver el contacto.",
                "Elige a alguien para que eyacule en la parte de tu cuerpo que más te guste.",
                "Quédate en una posición vulnerable y deja que el grupo te toque el sexo.",
                "Practica un oral a alguien mientras otra persona te penetra con un juguete.",
                "Masturba a dos personas a la vez (piel con piel) hasta que una acabe.",
                "Penetra a alguien y cambia de posición cada vez que el grupo aplauda.",
                "Deja que alguien lama tu sexo mientras tú lamas el de otra persona.",
                "Dale 5 nalgadas fuertes a alguien y luego bésale su zona íntima.",
                "Haz que la persona que elijas llegue al orgasmo usando solo tu boca.",
                "Ten sexo con alguien mientras el resto del grupo les acaricia a ambos.",
                "Deja que todos los presentes te den un beso o lametón en tu zona íntima.",
                "Elige a tu pareja favorita y tengan el sexo más ruidoso frente al grupo.",
                "Deja que tres personas te besen zonas íntimas simultáneamente",
                "Ten sexo oral mutuo (69) con alguien mientras el grupo mira",
                "Masturba a dos personas al mismo tiempo hasta que uno gima",
                "Deja que el grupo te desnude completamente y te toque por turnos",
                "Penetra a alguien (o déjate penetrar) en la posición que el grupo vote",
                "Haz un trío: tú en medio siendo estimulado/a por ambos lados",
                "Lame los genitales de cada persona del grupo por 10 segundos",
                "Deja que alguien eyacule en tu boca frente a todos",
                "Organiza una cadena: cada uno estimula al siguiente mientras es estimulado",
                "Ten sexo con alguien mientras otra persona te da sexo oral"
            ],
            verdad: [
                "¿Qué es lo que más te daría morbo que te hicieran dos personas?",
                "¿Con quién de aquí pasarías ahora mismo a otra habitación?",
                "¿Quién crees que llegaría primero al orgasmo en una orgía?",
                "¿Cuál es tu mayor fantasía sexual no cumplida?",
                "¿A quién de aquí le pedirías que te penetrara ahora mismo?",
                "¿Te gustaría grabar lo que pase en esta habitación hoy?",
                "¿Qué juguete sexual compartirías con todos los presentes?",
                "¿Quién del grupo crees que tiene el mejor miembro o sexo?",
                "¿Alguna vez has deseado recibir un bukake o lluvia dorada?",
                "¿Estás listo/a para perder el control con todo el grupo?",
                "¿Quién de aquí crees que tiene la lengua más hábil?",
                "¿Qué es lo más extremo que estarías dispuesto a hacer hoy aquí?",
                "¿Te gustaría que alguien del grupo grabara mientras lo haces?",
                "¿Con qué dos personas harías un sándwich (tú en medio) ahora?",
                "¿Quién de aquí crees que tiene el orgasmo más escandaloso?",
                "¿A quién del grupo le permitirías que eyaculara sobre ti?",
                "¿Te gustaría ver a tu pareja (si está aquí) con alguien más?",
                "¿Cuál es la zona más prohibida que dejarías que te tocaran hoy?",
                "¿Quién de aquí crees que tiene más resistencia sexual?",
                "¿Estarías dispuesto/a a participar en una orgía ahora mismo?",
                "¿Con quién de aquí tendrías sexo anal por primera vez?",
                "¿Te gustaría que alguien del grupo terminara en tu espalda?",
                "¿Quién del grupo crees que tiene el sabor más adictivo?",
                "¿Alguna vez has hecho un trío con penetración doble?",
                "¿Qué es lo que más te excita de que otros te vean acabar?",
                "¿A quién de aquí dejarías que te grabara teniendo sexo?",
                "¿Te gustaría participar en un intercambio de fluidos grupal?",
                "¿Quién de aquí crees que es el más dotado/estrecho?",
                "¿Prefieres el sexo grupal con conocidos o con extraños?",
                "¿Qué es lo más salvaje que has hecho en una orgía?",
                "¿A quién de aquí invitarías a que te usara a su antojo?",
                "¿Te gustaría ver a dos personas de aquí teniendo sexo real?",
                "¿Quién tiene la cara de orgasmo más sexy según tu imaginación?",
                "¿Cuál es tu límite absoluto en el sexo grupal?",
                "¿Te gustaría recibir sexo oral de dos personas a la vez?",
                "¿A quién de aquí le pedirías que te azote fuerte sin ropa?",
                "¿Cuál es la palabra que más te excita escuchar en una orgía?",
                "¿Qué posición grupal crees que es la más placentera?",
                "¿Te atrae la idea de ser el centro de una ronda de sexo oral?",
                "¿Estás listo/a para que esta noche sea inolvidable para todos?",
                "¿Cuántas personas del grupo te gustaría penetrar/que te penetren hoy?",
                "¿Estarías dispuesto/a a que todos acaben en ti/sobre ti?",
                "¿Cuál es tu límite: cuántas personas a la vez podrías manejar?",
                "¿Te gustaría un bukake con todos los del grupo?",
                "¿A quién del grupo le darías tu virginidad anal?",
                "¿Te excitaría una orgía donde todos participen contigo?",
                "¿Dejarías que te penetraran por ambos lados al mismo tiempo?",
                "¿Quién del grupo crees que aguanta más tiempo sin acabar?",
                "¿Te gustaría grabar un video porno con personas de aquí?",
                "¿Cuál es la fantasía más extrema que harías con este grupo?"
            ]
        }
    }
};
